### ISSUE TITLE
Scheduled Start not working - Response status code does not indicate success: 400 (Bad Request)

### ISSUE THREAD

**Issue by oramoss** [microsoft/startstopv2-deployments#7] opened 2021-03-26 17:01 UTC
I've just installed the latest code into public cloud using the appropriate button from the website.

It's a Hub and Spoke topology of Subscriptions and I've installed it into the Hub Subscription with a view to using it to manage VMs in the Hub and Spokes.

I've tried to run it for a Scheduled Resource Group level for the Development Spoke VMs which are in one Resource Group.

The JSON payload (redacted) is:

{
  "Action": "stop",
  "EnableClassic": false,
  "RequestScopes": {
    "ExcludedVMLists": [],
    "ResourceGroups": [
      "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myresourcegroup-rg/"
    ]
  }
}

I've given the Function App Contributor role on the Development Spoke Subscription (for now - will reduce but trying to get it to work initially).

I scheduled a run by editing the "ststv2_vms_Scheduled_stop" Logic App to configure the timings and enter the JSON payload, which validated and saved successfully.

I enabled the Logic App and it was executed on the schedule.

It fails with this error in the Logic App output:

{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Response status code does not indicate success: 400 (Bad Request).",
  "ExceptionType": "System.Net.Http.HttpRequestException",
  "StackTrace": "   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n   at StartStopAzureFunctions.Clients.AzureVirtualMachineClient.GetSubscriptionClassicVirtualMachinesAsync(String subscriptionId) in D:\\a\\1\\s\\StartStopAzureFunctions\\Clients\\AzureVirtualMachineClient.cs:line 151\r\n   at StartStopAzureFunctions.Clients.AzureVirtualMachineClient.GetSubscriptionVirtualMachinesAsync(String subscriptionId) in D:\\a\\1\\s\\StartStopAzureFunctions\\Clients\\AzureVirtualMachineClient.cs:line 99\r\n   at StartStopAzureFunctions.BusinessLogic.UserRequestTranslatorBL.GetAccessibleVmsForSubscriptionScopesAsync(IEnumerable`1 subscriptionIds) in D:\\a\\1\\s\\StartStopAzureFunctions\\BusinessLogic\\UserRequestTranslatorBL.cs:line 82\r\n   at StartStopAzureFunctions.Workflows.VirtualMachineScheduledRequestWorkflow.StartWorkflowAsync(ScheduledRequest scheduledRequest) in D:\\a\\1\\s\\StartStopAzureFunctions\\Workflows\\VirtualMachineScheduledRequestWorkflow.cs:line 81\r\n   at StartStopAzureFunctions.ScheduledRequestFunction.RunAsync(ScheduledRequest scheduledRequest) in D:\\a\\1\\s\\StartStopAzureFunctions\\ScheduledRequestFunction.cs:line 40"
}

**Comment by parojasmsft** [comment] 2021-03-26 17:24
Hi Oramoss,

I have notified our dev team of the issue so they can look into it.

**Comment by oramoss** [comment] 2021-04-26 22:08
Is this fixed now then? If so, what was the resolution and how do I get it installed please?

**Comment by balas77** [comment] 2021-04-26 22:29
Sorry accidently closed it.

**Comment by balas77** [comment] 2021-04-26 22:30
Did the start operation was working fine for you?

**Comment by balas77** [comment] 2021-04-26 22:32
From your payload the action was mentioned as stop so checking on the status of the start operation

**Comment by oramoss** [comment] 2021-04-27 07:24
start and stop both fail in same way. Thanks for reopening.

**Comment by oramoss** [comment] 2021-04-27 07:24
I was trying to do it on a subscription which wasn't the one where the software is installed and thought it might be that but also tried for same schema last night and that has same issues.

**Comment by balas77** [comment] 2021-04-27 23:34
Hey, can you make sure you have added the managed identity of azure functions with role as **contributor** into other subscriptions?

https://github.com/microsoft/startstopv2-deployments/blob/main/README.md#enable-multi-subscription-support

**Comment by oramoss** [comment] 2021-04-28 10:02
Was already Contributor on the two subscriptions (the one in which the Function App is installed and one it is not installed).

**Comment by balas77** [comment] 2021-04-28 20:55
Are they in same tenant?

**Comment by oramoss** [comment] 2021-04-28 21:22
Yes, same tenant.

**Comment by balas77** [comment] 2021-04-29 00:06
Just now tried to test the same behavior on our side and it works fine. Probably next step is to find the logs from the function/monitor (as mentioned in the below link) to figure out whats going on.

https://docs.microsoft.com/en-us/azure/azure-functions/start-stop-vms/troubleshoot

**Comment by oramoss** [comment] 2021-04-29 07:30
Article suggests looking through logs for the "Scheduled" HTTP function...there are no errors showing against that function, for it's entire history.

![image](https://user-images.githubusercontent.com/19692110/116514977-9c577b00-a8c3-11eb-9cf2-f3a76d051732.png)

Screen only shows logs for last 20 invocations so I click on Run query in App Insights to see the older ones...I find the ones that relate to the errored run and they show the same 500 return code but there are no details of logs/messages to dig into...doesn't seem to help.

Leave with me to dig...

**Comment by balas77** [comment] 2021-04-30 18:22
Can we have a quick call in teams? Would like to see whats going on and help you to unblock. Not sure what time zone you're currently in but can meet either today or Monday so please let me know.

**Comment by oramoss** [comment] 2021-04-30 18:31
Hi

I could do a call on Monday sometime - I'm in UK so it's now 19:31 here.

Thanks
Jeff

**Comment by balas77** [comment] 2021-04-30 20:32
Cool then I will setup meeting on our Monday morning 10am March 3rd which will be 6pm monday your time, rite? can you please share your email id to invite you?

**Comment by oramoss** [comment] 2021-05-01 15:24
jeff.moss@azurepremium.com 6pm Monday UK time is fine

**Comment by balas77** [comment] 2021-05-04 01:42
Hey Jeff,

Thanks for joining the meeting. I am happy to say that we have fixed the bug and updated the package and thanks for helping us to find this bug.

We haven't tested this in a subscription where classic provider was disabled/not supported which is the root cause of this issue.

Will it be fine for you to do the new deployment of this solution? Our Auto-Update feature (which allows customer to get the updates without re-installing) is disabled for now hence asking you to re-install in a new resource group.

After installing please give it a try and update us on the outcome!

**Comment by oramoss** [comment] 2021-05-04 07:03
Will try shortly....

**Comment by oramoss** [comment] 2021-05-04 08:01
That worked, at least to use scheduled start/stop to start a VM in the Development Spoke, from the Hub installation.

A couple of issues:

1. When I installed I first removed all resources from the target resource group (where I install this facility). The resource group was then empty prior to installing. The deployment ran with errors - image below. Complaints about inability to change scope...not sure why...but the facility worked for scheduled start/stop as I say.
2. When running across subscriptions - as I tested - you advise giving Contributor role at Subscription level, to the Function App. Can we be a little less generous on the privileges - least privileges principle wise?
![image](https://user-images.githubusercontent.com/19692110/116975321-5fbac380-acb7-11eb-8b99-eb469adfdaf5.png)

**Comment by balas77** [comment] 2021-05-04 22:41
Glad that it works finally! 

Comments on your points

1. I think that error is ok for now. The recommended way is to delete the RG instead of deleting the individual resource. These alerts/queries wont show up in the RG hence when you redeploy in the same RG it was unable to override hence that issue. I will check and improve the experience.
2. Thanks for the feedback. I will explore the options on this. Probably "Virtual Machine Contributor" would be the fit but today we are doing few other operations like cost savings which needs to call other API's etc which might benefit of having the generic contributor perms.

**Comment by oramoss** [comment] 2021-05-05 07:08
Yeah, I did just remove the resources in the RG rather than the RG itself - fair enough. Maybe if I'd checked show hidden I would have seen them and removed them as well.
No problem - for now Contributor is fine but clearly better if it can be locked down in time.

Many thanks for the swift response of your team.
Regards
Jeff

**Comment by balas77** [comment] 2021-05-05 17:21
Thanks & happy to work with you Jeff! I will go ahead and close this issue!

**Closed** 2021-05-05 17:22 UTC
