### ISSUE TITLE
Did anyone get this to work ?

### ISSUE THREAD

**Issue by pvansteenkiste** [microsoft/startstopv2-deployments#8] opened 2021-04-26 11:05 UTC
When trying to have a few vms stopped the logic app runs into this error:

{
  "Message": "An error has occurred.",
  "ExceptionMessage": "Response status code does not indicate success: 400 (Bad Request).",
  "ExceptionType": "System.Net.Http.HttpRequestException",
  "StackTrace": "   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()\r\n   at StartStopAzureFunctions.Clients.AzureVirtualMachineClient.GetSubscriptionClassicVirtualMachinesAsync(String subscriptionId) in D:\\a\\1\\s\\StartStopAzureFunctions\\Clients\\AzureVirtualMachineClient.cs:line 151\r\n   at StartStopAzureFunctions.Clients.AzureVirtualMachineClient.GetSubscriptionVirtualMachinesAsync(String subscriptionId) in D:\\a\\1\\s\\StartStopAzureFunctions\\Clients\\AzureVirtualMachineClient.cs:line 99\r\n   at StartStopAzureFunctions.BusinessLogic.UserRequestTranslatorBL.GetAccessibleVmsForSubscriptionScopesAsync(IEnumerable`1 subscriptionIds) in D:\\a\\1\\s\\StartStopAzureFunctions\\BusinessLogic\\UserRequestTranslatorBL.cs:line 82\r\n   at StartStopAzureFunctions.Workflows.VirtualMachineScheduledRequestWorkflow.StartWorkflowAsync(ScheduledRequest scheduledRequest) in D:\\a\\1\\s\\StartStopAzureFunctions\\Workflows\\VirtualMachineScheduledRequestWorkflow.cs:line 81\r\n   at StartStopAzureFunctions.ScheduledRequestFunction.RunAsync(ScheduledRequest scheduledRequest) in D:\\a\\1\\s\\StartStopAzureFunctions\\ScheduledRequestFunction.cs:line 40"
}

**Comment by parojasmsft** [comment] 2021-04-26 14:24
Hi pvansteenkiste,

The team will look into this and get back to you.

**Comment by parojasmsft** [comment] 2021-04-26 17:38
Are you internal microsoft or an external customer. Please contact us at startstopv2team@microsoft.com with your subscription id and payload so we can look further into it.

**Comment by balas77** [comment] 2021-04-26 18:00
Hi pvansteenkiste,

Is this the first time you're using our solution to start or stop? Can you share your payload (probably to the email shared above)?

**Comment by pvansteenkiste** [comment] 2021-04-27 07:15
Hi,

Subscription used:

c0c00520-89d1-47b4-b4ef-49bdbed805d3

the payload I ran:

"Function-Try": {
                "actions": {
                    "Scheduled": {
                        "inputs": {
                            "body": {
                                "Action": "stop",
                                "EnableClassic": false,
                                "RequestScopes": {
                                    "ExcludedVMLists": [],
                                    "VMLists": [
                                        "/subscriptions/f5692496-a740-491f-a68f-140b1fa51049/resourceGroups/renson-od-dev-extended-warranty-rg/providers/Microsoft.Compute/virtualMachines/renson-od-dev-extended-warranty-vm",
                                        "/subscriptions/ad0a4f40-1ff0-4dc5-9a5d-ef517962a7f6/resourceGroups/renson-od-stg-extended-warranty-rg/providers/Microsoft.Compute/virtualMachines/renson-od-stg-extended-warranty-vm"
                                    ]
                                }
                            },
                            "function": {
                                "id": "/subscriptions/c0c00520-89d1-47b4-b4ef-49bdbed805d3/resourceGroups/renson-it-startstop-rg/providers/Microsoft.Web/sites/rensonstopstartvm/functions/Scheduled"
                            }
                        },
                        "runAfter": {},
                        "type": "Function"
                    }
                },
                "runAfter": {},
                "type": "Scope"


(I disabled the Logic app again, but it was enabled at runtime)


best regards,

Philippe
________________________________

**Comment by balas77** [comment] 2021-04-27 23:27
Hi Philippe,

So looks like you've configured start/stop v2 in subscription A and taking action on VMs in subscription B and C. So want to make sure you have performed the pre-steps on adding the managed identity of subscription A in B and C manually. Here is the instructions for it 
https://github.com/microsoft/startstopv2-deployments/blob/main/README.md#enable-multi-subscription-support 

Once you perform the above steps please give it a try and let us know.

Thanks!

**Comment by pvansteenkiste** [comment] 2021-04-28 06:19
Hi,

I already followed the instructions to add the managed identity as owner on the other subscriptions so that shouldn’t be the issue …

Kind Regards,

Philippe

Van: balas77 ***@***.***>
Datum: woensdag, 28 april 2021 om 01:27
Aan: microsoft/startstopv2-deployments ***@***.***>
CC: Philippe Vansteenkiste ***@***.***>, Author ***@***.***>
Onderwerp: Re: [microsoft/startstopv2-deployments] Did anyone get this to work ? (#8)

Hi Philippe,

So looks like you've configured start/stop v2 in subscription A and taking action on VMs in subscription B and C. So want to make sure you have performed the pre-steps on adding the managed identity of subscription A in B and C manually. Here is the instructions for it
https://github.com/microsoft/startstopv2-deployments/blob/main/README.md#enable-multi-subscription-support

Once you perform the above steps please give it a try and let us know.

Thanks!

**Comment by balas77** [comment] 2021-04-28 20:55
Are they in same tenant?

**Comment by pvansteenkiste** [comment] 2021-04-29 06:36
Yes they are :-)

Verstuurd vanaf mijn iPhone

Op 28 apr. 2021 om 22:55 heeft balas77 ***@***.***> het volgende geschreven:

﻿

Are they in same tenant?

**Comment by balas77** [comment] 2021-05-04 01:44
Hi Philippe,

We found the root cause of this issue and fix has been updated in the deployment package.

Will it be fine for you to do the new deployment of this solution? Our Auto-Update feature (which allows customer to get the updates without re-installing) is disabled for now hence asking you to re-install in a new resource group.

After installing please give it a try and update us on the outcome!

**Comment by balas77** [comment] 2021-05-04 22:43
Hi Philippe,

Do you have any updates on this? Please make sure you do new installation into new RG and later you can delete the old RG itself.

**Comment by balas77** [comment] 2021-05-14 22:16
Hi Philippe,

Can you please let me know if this issue still persist or can we close it now?

**Comment by pvansteenkiste** [comment] 2021-05-15 09:37
Hi,

You can surely close this ticket, thank you for your help, I’m confident the issue is resolved, I guess others will also benefit 😃

Best Regards,

Philippe

Van: balas77 ***@***.***>
Datum: zaterdag, 15 mei 2021 om 00:16
Aan: microsoft/startstopv2-deployments ***@***.***>
CC: Philippe Vansteenkiste ***@***.***>, Author ***@***.***>
Onderwerp: Re: [microsoft/startstopv2-deployments] Did anyone get this to work ? (#8)

Hi Philippe,

Can you please let me know if this issue still persist or can we close it now?

**Comment by balas77** [comment] 2021-05-15 17:43
Happy working with you and thanks for your contribution on this!

**Closed by balas77** 2021-05-15 17:43 UTC
