### ISSUE TITLE
The subscription 'Sub id' could not be found."

### ISSUE THREAD

**Issue by nhoj01** [microsoft/startstopv2-deployments#5] opened 2021-03-12 13:51 UTC
Hello:

I am trying to use the function app in Azure Gov using the payload below, and I keep getting an error that the subscription is not found. Is this not usable on Azure Government? 

{
  "Action": "start",
  "EnableClassic": false,
  "RequestScopes": {
    "ExcludedVMLists": [],
    "Subscriptions": [
      "/subscriptions/my-subscription-id/"
    ]
 }
}

 "StackTrace": "   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations.ListWithHttpMessagesAsync(ODataQuery`1 odataQuery, Dictionary`2 customHeaders, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperationsExtensions.ListAsync(IResourcesOperations operations, ODataQuery`1 odataQuery, CancellationToken cancellationToken)\r\n   at StartStopAzureFunctions.Clients.AzureVirtualMachineClient.GetSubscriptionArmVirtualMachinesAsync(String subscriptionId) in D:\\a\\1\\s\\StartStopAzureFunctions\\Clients\\AzureVirtualMachineClient.cs:line 110\r\n   at StartStopAzureFunctions.Clients.AzureVirtualMachineClient.GetSubscriptionVirtualMachinesAsync(String subscriptionId) in D:\\a\\1\\s\\StartStopAzureFunctions\\Clients\\AzureVirtualMachineClient.cs:line 98\r\n   at StartStopAzureFunctions.BusinessLogic.UserRequestTranslatorBL.GetAccessibleVmsForSubscriptionScopesAsync(IEnumerable`1 subscriptionIds) in D:\\a\\1\\s\\StartStopAzureFunctions\\BusinessLogic\\UserRequestTranslatorBL.cs:line 82\r\n   at StartStopAzureFunctions.Workflows.VirtualMachineScheduledRequestWorkflow.StartWorkflowAsync(ScheduledRequest scheduledRequest) in D:\\a\\1\\s\\StartStopAzureFunctions\\Workflows\\VirtualMachineScheduledRequestWorkflow.cs:line 81\r\n   at StartStopAzureFunctions.ScheduledRequestFunction.RunAsync(ScheduledRequest scheduledRequest, CloudQueue orchestrationRequestQueue, CloudTable requestStoreTable) in D:\\a\\1\\s\\StartStopAzureFunctions\\ScheduledRequestFunction.cs:line 41"
}

**Comment by svarga-msft** [comment] 2021-03-12 19:03
Hi, the solution does support Azure Government subscriptions. Did you deploy using the deployment button for government subscriptions?

I'd be happy to help you get this sorted out.

**Comment by svarga-msft** [comment] 2021-03-12 19:04
I see you provided the stack trace, but could you provide the exact error that you received? There are a variety of subscription related error messages so the exact one will help us narrow it down.

**Comment by nhoj01** [comment] 2021-03-12 21:28
@svarga-msft  I deployed using the Production - Fairfax/UsGov (Preview)

I'm a bit new at Azure Functions/Logic apps is there a specific error code that you need and how would I find it?

The logic app is showing status 500
{
  "Message": "An error has occurred.",
  "ExceptionMessage": "The subscription 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' could not be found.",

**Comment by svarga-msft** [comment] 2021-03-12 21:31
Just to confirm, the subscription that you deployed to is the same subscription that you're using in the payload?

**Comment by nhoj01** [comment] 2021-03-12 22:12
Correct it is the same subscription.

**Comment by svarga-msft** [comment] 2021-03-12 22:57
The solution uses logic apps to call an Azure Function. From the stack trace it looks like the function is failing on the call to pull the Virtual Machines in the provided subscription.

Please feel free to send our team an email here: startstopv2team@microsoft.com

We can hopefully work with you to get it sorted out, then update this thread for future users.

**Comment by balas77** [comment] 2021-03-15 23:48
We found the root cause of this issue and sorry for the inconvenience caused. 

Please follow the below instructions to make quick update in the function app configuration (this is to make sure you can reuse the same deployment). 

Open the azure portal and navigate to the resource group that you had our V2 deployment.
•	Open the function app  Configuration (under Settings)
•	Do the below changes to the configuration properties
o	Click & Change the property name from **AzureClientOptions:AzureEnvironment** to **AzureClientOptions:AzureEnv**
o	Click the StorageOptions:StorageAccountConnectionString property name and append the value at the end. Please make 
         sure keep the existing value as is and only append the new value at the end.
 
o	;EndpointSuffix=core.usgovcloudapi.net

We have also fixed this and updated the package in the GitHub which you can also deploy the new instance if needed!

**Comment by balas77** [comment] 2021-04-26 18:01
I hope this is resolved now and hence closing this issue!

**Closed by balas77** 2021-04-26 18:01 UTC
